// <auto-generated />
using MASFinalWebApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MASFinalWebApp.Migrations
{
    [DbContext(typeof(InsurexDbContext))]
    partial class InsurexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MASFinalWebApp.Models.Insurance", b =>
                {
                    b.Property<int>("InsuranceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GeneralTermsAndConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("InsuranceAmount")
                        .HasColumnType("real");

                    b.Property<string>("InsuranceRange")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsuranceID");

                    b.ToTable("Insurance");
                });

            modelBuilder.Entity("MASFinalWebApp.Models.InsurancePackage", b =>
                {
                    b.Property<int>("InsurancePackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsurancePackageID");

                    b.ToTable("InsurancePackage");
                });

            modelBuilder.Entity("MASFinalWebApp.Models.InsurancesInPackages", b =>
                {
                    b.Property<int>("InsuranceID")
                        .HasColumnType("int");

                    b.Property<int>("InsurancePackageID")
                        .HasColumnType("int");

                    b.HasKey("InsuranceID", "InsurancePackageID");

                    b.HasIndex("InsurancePackageID");

                    b.ToTable("InsurancesInPackages");
                });

            modelBuilder.Entity("MASFinalWebApp.Models.InsurancesInPackages", b =>
                {
                    b.HasOne("MASFinalWebApp.Models.Insurance", "Insurances")
                        .WithMany("InsurancesInPackages")
                        .HasForeignKey("InsuranceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MASFinalWebApp.Models.InsurancePackage", "InsurancePackage")
                        .WithMany("InsurancesInPackages")
                        .HasForeignKey("InsurancePackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePackage");

                    b.Navigation("Insurances");
                });

            modelBuilder.Entity("MASFinalWebApp.Models.Insurance", b =>
                {
                    b.Navigation("InsurancesInPackages");
                });

            modelBuilder.Entity("MASFinalWebApp.Models.InsurancePackage", b =>
                {
                    b.Navigation("InsurancesInPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
